# Generated by Django 5.0 on 2024-01-01 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petid', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('place', models.CharField(max_length=120)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Content', 'Content'), ('Sad', 'Sad')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('water_intake', models.DecimalField(decimal_places=0, max_digits=4)),
                ('food_intake', models.DecimalField(decimal_places=3, max_digits=5)),
                ('defecation', models.CharField(choices=[('Diarrhea', 'Diarrhea'), ('Normal', 'Normal'), ('Constipation', 'Constipation')], max_length=20)),
                ('abnormality', models.TextField()),
                ('medical_record', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IotFoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('food_intake', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='IotWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('water_intake', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='IotWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=60)),
                ('petid', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=36)),
                ('breed', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutral', 'Neutral')], max_length=10)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=36)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Hat', 'Hat'), ('Clothes', 'Clothes'), ('Background', 'Background')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=60)),
                ('money', models.DecimalField(decimal_places=0, default=1000, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=60)),
                ('productid', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=10)),
                ('posX', models.DecimalField(decimal_places=0, max_digits=4)),
                ('posY', models.DecimalField(decimal_places=0, max_digits=4)),
                ('width', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('height', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('zIndex', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('equipped', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
            ],
        ),
    ]
