# Generated by Django 5.0 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
    ]
