# Generated by Django 5.0 on 2023-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotfoodintake',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='iotwaterintake',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='iotweight',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
