# Generated by Django 5.0 on 2024-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_userproduct_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
