# Generated by Django 5.0 on 2023-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_product_image_alter_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
