# Generated by Django 5.0 on 2023-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_diary_date_alter_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
