# Generated by Django 5.0 on 2024-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_product_productid_alter_userproduct_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
