# Generated by Django 5.0 on 2023-12-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='height',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='width',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='zIndex',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
