name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 107.191.60.115 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: SSH into Remote Server and Execute Commands
      run: |
        ssh pd@107.191.60.115 'cd /path/to/your/repo && git pull origin master && ./build.sh'
